### ISSUE TITLE
THANK you!

### ISSUE THREAD

**Issue by blubbll** [PoweredSoft/DynamicLinq#1]
Thank you for creating this awesome library.
I've been trying to find a way to make dynamic linq queries (dynamic calls on table names) for days
and finally found your solution.
This makes the search function in my webapi waaay more dynamic.

Thanks!

**Comment by dlebee** [comment]
Hey no problem :)

**Comment by dlebee** [comment]
@blubbll, you might be interested in this as well github.com/PoweredSoft/DynamicQuery, there is a sample with it being used with .net core asp
