### ISSUE TITLE
add Not Contains

### ISSUE THREAD

**Issue by Jon-Galloway** [PoweredSoft/DynamicLinq#4]
As a developer I would like if NotContains were a ConditionOperator so that I can create exclusion queries.

**Comment by dlebee** [comment]
I'll look into it.

**Comment by Jon-Galloway** [comment]
I have the code ready to go.  Can I open a Pull Request?

**Comment by Jon-Galloway** [comment]
Getting 403 attempting to push new branch to this repo.

**Comment by dlebee** [comment]
You could, but I have an idea that you might like and alot might too, what about h aving some kind of negate option, that regardless of the ConditionalOperator, you can just negate it.

So the condition operator would be Contains with the negate option to true?

**Comment by Jon-Galloway** [comment]
This is sufficient for my use case:

```
            else if (conditionOperator == ConditionOperators.NotContains)
            {
                if (member.Type == stringType && stringComparision.HasValue)
                    ret = Expression.GreaterThan(Expression.Not(Expression.Call(member, Constants.IndexOfMethod, constant, Expression.Constant(stringComparision.Value))), Expression.Constant(-1));
                else
                    ret = Expression.Not(Expression.Call(member, Constants.ContainsMethod, constant));
            }

```

Have tests also.

**Comment by Jon-Galloway** [comment]
> You could, but I have an idea that you might like and alot might too, what about h aving some kind of negate option, that regardless of the ConditionalOperator, you can just negate it.
> 
> So the condition operator would be Contains with the negate option to true?
> 
> This means you could do StartsWith with a negate, == !StartsWith

This proposal may be a breaking change for others .. as there is a NotEqualTo which would then become obsolete, etc....

**Comment by Jon-Galloway** [comment]
(Would suggest to keep the cleaner naming.  That's one of the things I like about this repo.)

**Comment by dlebee** [comment]
I guess, for now I was trying to keep the condition operators based on the expression library, I like the idea of negating as well, I can probably add both. It shouldn't take too long to run unit testing on it either, I'll see what I can do, maybe check again in 1-2 hours?

**Comment by Jon-Galloway** [comment]
OK.  Again I have the code and Unit Tests but completely understand if you are not open to Pull Requests at this time.

Will check back later.  Thanks for all your hard work on this project!

**Comment by Jon-Galloway** [comment]
diff --git a/PoweredSoft.DynamicLinq.Test/ShortcutTests.cs b/PoweredSoft.DynamicLinq.Test/ShortcutTests.cs
index 9025dda..63156b2 100644
--- a/PoweredSoft.DynamicLinq.Test/ShortcutTests.cs
+++ b/PoweredSoft.DynamicLinq.Test/ShortcutTests.cs
@@ -170,5 +170,29 @@ namespace PoweredSoft.DynamicLinq.Test
             var q3b = Persons.AsQueryable().Where(t => t.LastName.Contains("ee") || t.LastName.Contains("ar"));
             QueryableAssert.AreEqual(q3, q3b);
         }
+
+        [TestMethod]
+        public void NotContains()
+        {
+            var q1 = Persons.AsQueryable().Query(t => t.NotContains("LastName", "ee"));
+            var q1b = Persons.AsQueryable().Where(t => !t.LastName.Contains("ee"));
+            QueryableAssert.AreEqual(q1, q1b);
+
+            var q2 = Persons.AsQueryable().Query(t => t.NotContains("LastName", "ee").AndNotContains("FirstName", "vid"));
+            var q2b = Persons.AsQueryable().Where(t => !t.LastName.Contains("ee") && !t.FirstName.Contains("vid"));
+            QueryableAssert.AreEqual(q2, q2b);
+
+            var q3 = Persons.AsQueryable().Query(t => t.NotContains("LastName", "ee").OrNotContains("LastName", "ar"));
+            var q3b = Persons.AsQueryable().Where(t => !t.LastName.Contains("ee") || !t.LastName.Contains("ar"));
+            QueryableAssert.AreEqual(q3, q3b);
+        }
+
+        [TestMethod]
+        public void ContainsAndNotContains()
+        {
+            var q1 = Persons.AsQueryable().Query(t => t.Contains("LastName", "s").AndNotContains("LastName", "r"));
+            var q1b = Persons.AsQueryable().Where(t => t.LastName.Contains("s") && !t.LastName.Contains("r"));
+            QueryableAssert.AreEqual(q1, q1b);
+        }
     }
 }
diff --git a/PoweredSoft.DynamicLinq.Test/StringComparision.cs b/PoweredSoft.DynamicLinq.Test/StringComparision.cs
index a6163a1..431d054 100644
--- a/PoweredSoft.DynamicLinq.Test/StringComparision.cs
+++ b/PoweredSoft.DynamicLinq.Test/StringComparision.cs
@@ -60,6 +60,22 @@ namespace PoweredSoft.DynamicLinq.Test
             QueryableAssert.AreEqual(a, b, "CaseInsensitive");
         }
 
+        [TestMethod]
+        public void NotContains()
+        {
+            IQueryable<MockPersonObject> a, b;
+
+            // case sensitive.
+            a = Persons.AsQueryable().Query(t => t.NotContains("FirstName", "vi", stringComparision: null));
+            b = Persons.AsQueryable().Where(t => !t.FirstName.Contains("vi"));
+            QueryableAssert.AreEqual(a, b, "CaseSensitive");
+
+            // not case sensitive
+            a = Persons.AsQueryable().Query(t => t.NotContains("FirstName", "VI", stringComparision: StringComparison.OrdinalIgnoreCase));
+            b = Persons.AsQueryable().Where(t => t.FirstName.IndexOf("VI", StringComparison.OrdinalIgnoreCase) == -1);
+            QueryableAssert.AreEqual(a, b, "CaseInsensitive");
+        }
+
         [TestMethod]
         public void StartsWith()
         {
diff --git a/PoweredSoft.DynamicLinq/Constants.cs b/PoweredSoft.DynamicLinq/Constants.cs
index 8e5c05e..f2f23ca 100644
--- a/PoweredSoft.DynamicLinq/Constants.cs
+++ b/PoweredSoft.DynamicLinq/Constants.cs
@@ -16,6 +16,7 @@ namespace PoweredSoft.DynamicLinq
         LessThan,
         LessThanOrEqual,
         Contains,
+        NotContains,
         StartsWith,
         EndsWith,
         In,
diff --git a/PoweredSoft.DynamicLinq/Fluent/Where/WhereBuilder.shortcuts.cs b/PoweredSoft.DynamicLinq/Fluent/Where/WhereBuilder.shortcuts.cs
index 658f42b..88c80b0 100644
--- a/PoweredSoft.DynamicLinq/Fluent/Where/WhereBuilder.shortcuts.cs
+++ b/PoweredSoft.DynamicLinq/Fluent/Where/WhereBuilder.shortcuts.cs
@@ -97,6 +97,17 @@ namespace PoweredSoft.DynamicLinq.Fluent
             => Or(path, ConditionOperators.Contains, value, convertStrategy: convertStrategy, collectionHandling: collectionHandling, stringComparision: stringComparision);
         #endregion
 
+        #region not contains
+        public WhereBuilder NotContains(string path, object value, QueryConvertStrategy convertStrategy = QueryConvertStrategy.ConvertConstantToComparedPropertyOrField, QueryCollectionHandling collectionHandling = QueryCollectionHandling.Any, StringComparison? stringComparision = null)
+            => And(path, ConditionOperators.NotContains, value, convertStrategy: convertStrategy, collectionHandling: collectionHandling, stringComparision: stringComparision);
+
+        public WhereBuilder AndNotContains(string path, object value, QueryConvertStrategy convertStrategy = QueryConvertStrategy.ConvertConstantToComparedPropertyOrField, QueryCollectionHandling collectionHandling = QueryCollectionHandling.Any, StringComparison? stringComparision = null)
+            => And(path, ConditionOperators.NotContains, value, convertStrategy: convertStrategy, collectionHandling: collectionHandling, stringComparision: stringComparision);
+
+        public WhereBuilder OrNotContains(string path, object value, QueryConvertStrategy convertStrategy = QueryConvertStrategy.ConvertConstantToComparedPropertyOrField, QueryCollectionHandling collectionHandling = QueryCollectionHandling.Any, StringComparison? stringComparision = null)
+            => Or(path, ConditionOperators.NotContains, value, convertStrategy: convertStrategy, collectionHandling: collectionHandling, stringComparision: stringComparision);
+        #endregion
+
         #region starts with
         public WhereBuilder StartsWith(string path, object value, QueryConvertStrategy convertStrategy = QueryConvertStrategy.ConvertConstantToComparedPropertyOrField, QueryCollectionHandling collectionHandling = QueryCollectionHandling.Any, StringComparison? stringComparision = null)
             => And(path, ConditionOperators.StartsWith, value, convertStrategy: convertStrategy, collectionHandling: collectionHandling, stringComparision: stringComparision);
diff --git a/PoweredSoft.DynamicLinq/Helpers/QueryableHelpers.cs b/PoweredSoft.DynamicLinq/Helpers/QueryableHelpers.cs
index d9985a6..d4d3f04 100644
--- a/PoweredSoft.DynamicLinq/Helpers/QueryableHelpers.cs
+++ b/PoweredSoft.DynamicLinq/Helpers/QueryableHelpers.cs
@@ -61,6 +61,13 @@ namespace PoweredSoft.DynamicLinq.Helpers
                 else
                     ret = Expression.Call(member, Constants.ContainsMethod, constant);
             }
+            else if (conditionOperator == ConditionOperators.NotContains)
+            {
+                if (member.Type == stringType && stringComparision.HasValue)
+                    ret = Expression.GreaterThan(Expression.Not(Expression.Call(member, Constants.IndexOfMethod, constant, Expression.Constant(stringComparision.Value))), Expression.Constant(-1));
+                else
+                    ret = Expression.Not(Expression.Call(member, Constants.ContainsMethod, constant));
+            }
             else if (conditionOperator == ConditionOperators.StartsWith)
             {
                 if (member.Type == stringType && stringComparision.HasValue)

**Comment by Jon-Galloway** [comment]
```
diff --git a/PoweredSoft.DynamicLinq.Test/ShortcutTests.cs b/PoweredSoft.DynamicLinq.Test/ShortcutTests.cs
index 9025dda..63156b2 100644
--- a/PoweredSoft.DynamicLinq.Test/ShortcutTests.cs
+++ b/PoweredSoft.DynamicLinq.Test/ShortcutTests.cs
@@ -170,5 +170,29 @@ namespace PoweredSoft.DynamicLinq.Test
             var q3b = Persons.AsQueryable().Where(t => t.LastName.Contains("ee") || t.LastName.Contains("ar"));
             QueryableAssert.AreEqual(q3, q3b);
         }
+
+        [TestMethod]
+        public void NotContains()
+        {
+            var q1 = Persons.AsQueryable().Query(t => t.NotContains("LastName", "ee"));
+            var q1b = Persons.AsQueryable().Where(t => !t.LastName.Contains("ee"));
+            QueryableAssert.AreEqual(q1, q1b);
+
+            var q2 = Persons.AsQueryable().Query(t => t.NotContains("LastName", "ee").AndNotContains("FirstName", "vid"));
+            var q2b = Persons.AsQueryable().Where(t => !t.LastName.Contains("ee") && !t.FirstName.Contains("vid"));
+            QueryableAssert.AreEqual(q2, q2b);
+
+            var q3 = Persons.AsQueryable().Query(t => t.NotContains("LastName", "ee").OrNotContains("LastName", "ar"));
+            var q3b = Persons.AsQueryable().Where(t => !t.LastName.Contains("ee") || !t.LastName.Contains("ar"));
+            QueryableAssert.AreEqual(q3, q3b);
+        }
+
+        [TestMethod]
+        public void ContainsAndNotContains()
+        {
+            var q1 = Persons.AsQueryable().Query(t => t.Contains("LastName", "s").AndNotContains("LastName", "r"));
+            var q1b = Persons.AsQueryable().Where(t => t.LastName.Contains("s") && !t.LastName.Contains("r"));
+            QueryableAssert.AreEqual(q1, q1b);
+        }
     }
 }
diff --git a/PoweredSoft.DynamicLinq.Test/StringComparision.cs b/PoweredSoft.DynamicLinq.Test/StringComparision.cs
index a6163a1..431d054 100644
--- a/PoweredSoft.DynamicLinq.Test/StringComparision.cs
+++ b/PoweredSoft.DynamicLinq.Test/StringComparision.cs
@@ -60,6 +60,22 @@ namespace PoweredSoft.DynamicLinq.Test
             QueryableAssert.AreEqual(a, b, "CaseInsensitive");
         }
 
+        [TestMethod]
+        public void NotContains()
+        {
+            IQueryable<MockPersonObject> a, b;
+
+            // case sensitive.
+            a = Persons.AsQueryable().Query(t => t.NotContains("FirstName", "vi", stringComparision: null));
+            b = Persons.AsQueryable().Where(t => !t.FirstName.Contains("vi"));
+            QueryableAssert.AreEqual(a, b, "CaseSensitive");
+
+            // not case sensitive
+            a = Persons.AsQueryable().Query(t => t.NotContains("FirstName", "VI", stringComparision: StringComparison.OrdinalIgnoreCase));
+            b = Persons.AsQueryable().Where(t => t.FirstName.IndexOf("VI", StringComparison.OrdinalIgnoreCase) == -1);
+            QueryableAssert.AreEqual(a, b, "CaseInsensitive");
+        }
+
         [TestMethod]
         public void StartsWith()
         {
diff --git a/PoweredSoft.DynamicLinq/Constants.cs b/PoweredSoft.DynamicLinq/Constants.cs
index 8e5c05e..f2f23ca 100644
--- a/PoweredSoft.DynamicLinq/Constants.cs
+++ b/PoweredSoft.DynamicLinq/Constants.cs
@@ -16,6 +16,7 @@ namespace PoweredSoft.DynamicLinq
         LessThan,
         LessThanOrEqual,
         Contains,
+        NotContains,
         StartsWith,
         EndsWith,
         In,
diff --git a/PoweredSoft.DynamicLinq/Fluent/Where/WhereBuilder.shortcuts.cs b/PoweredSoft.DynamicLinq/Fluent/Where/WhereBuilder.shortcuts.cs
index 658f42b..88c80b0 100644
--- a/PoweredSoft.DynamicLinq/Fluent/Where/WhereBuilder.shortcuts.cs
+++ b/PoweredSoft.DynamicLinq/Fluent/Where/WhereBuilder.shortcuts.cs
@@ -97,6 +97,17 @@ namespace PoweredSoft.DynamicLinq.Fluent
             => Or(path, ConditionOperators.Contains, value, convertStrategy: convertStrategy, collectionHandling: collectionHandling, stringComparision: stringComparision);
         #endregion
 
+        #region not contains
+        public WhereBuilder NotContains(string path, object value, QueryConvertStrategy convertStrategy = QueryConvertStrategy.ConvertConstantToComparedPropertyOrField, QueryCollectionHandling collectionHandling = QueryCollectionHandling.Any, StringComparison? stringComparision = null)
+            => And(path, ConditionOperators.NotContains, value, convertStrategy: convertStrategy, collectionHandling: collectionHandling, stringComparision: stringComparision);
+
+        public WhereBuilder AndNotContains(string path, object value, QueryConvertStrategy convertStrategy = QueryConvertStrategy.ConvertConstantToComparedPropertyOrField, QueryCollectionHandling collectionHandling = QueryCollectionHandling.Any, StringComparison? stringComparision = null)
+            => And(path, ConditionOperators.NotContains, value, convertStrategy: convertStrategy, collectionHandling: collectionHandling, stringComparision: stringComparision);
+
+        public WhereBuilder OrNotContains(string path, object value, QueryConvertStrategy convertStrategy = QueryConvertStrategy.ConvertConstantToComparedPropertyOrField, QueryCollectionHandling collectionHandling = QueryCollectionHandling.Any, StringComparison? stringComparision = null)
+            => Or(path, ConditionOperators.NotContains, value, convertStrategy: convertStrategy, collectionHandling: collectionHandling, stringComparision: stringComparision);
+        #endregion
+
         #region starts with
         public WhereBuilder StartsWith(string path, object value, QueryConvertStrategy convertStrategy = QueryConvertStrategy.ConvertConstantToComparedPropertyOrField, QueryCollectionHandling collectionHandling = QueryCollectionHandling.Any, StringComparison? stringComparision = null)
             => And(path, ConditionOperators.StartsWith, value, convertStrategy: convertStrategy, collectionHandling: collectionHandling, stringComparision: stringComparision);
diff --git a/PoweredSoft.DynamicLinq/Helpers/QueryableHelpers.cs b/PoweredSoft.DynamicLinq/Helpers/QueryableHelpers.cs
index d9985a6..d4d3f04 100644
--- a/PoweredSoft.DynamicLinq/Helpers/QueryableHelpers.cs
+++ b/PoweredSoft.DynamicLinq/Helpers/QueryableHelpers.cs
@@ -61,6 +61,13 @@ namespace PoweredSoft.DynamicLinq.Helpers
                 else
                     ret = Expression.Call(member, Constants.ContainsMethod, constant);
             }
+            else if (conditionOperator == ConditionOperators.NotContains)
+            {
+                if (member.Type == stringType && stringComparision.HasValue)
+                    ret = Expression.GreaterThan(Expression.Not(Expression.Call(member, Constants.IndexOfMethod, constant, Expression.Constant(stringComparision.Value))), Expression.Constant(-1));
+                else
+                    ret = Expression.Not(Expression.Call(member, Constants.ContainsMethod, constant));
+            }
             else if (conditionOperator == ConditionOperators.StartsWith)
             {
                 if (member.Type == stringType && stringComparision.HasValue)

```

**Comment by dlebee** [comment]
If you already did the hard work I don't see why not, are you saying the repository doe snot allow for pull requests?

**Comment by Jon-Galloway** [comment]
Correct.  It seems to not allow creation of new branch.  I get 403 / Unauthorized after submitting my Git-hub creds.  /shrug

**Comment by dlebee** [comment]
If you use the Pull Request menu does it work?

**Comment by Jon-Galloway** [comment]
That led me in the right direction.  Thanks!  Had to fork.

**Comment by dlebee** [comment]
I am still thinking of supporting both after merging with your code, what you think of this as well?

[TestMethod]
        public void NotContains()
        {
            var q1 = Persons.AsQueryable().Query(t => t.Contains("LastName", "ee", negate: true));
            var q1b = Persons.AsQueryable().Where(t => !t.LastName.Contains("ee"));
            QueryableAssert.AreEqual(q1, q1b);
        }

**Comment by Jon-Galloway** [comment]
Yeah!  I think it would be very-appropriate to support both.

**Comment by dlebee** [comment]
Both seems to pass all unit testing, i'll complete some last checks, and push up a version on nuget.

**Comment by dlebee** [comment]
@Jon-Galloway the nuget is getting updated, once you confirm all is good, I will close the issue.

**Comment by Jon-Galloway** [comment]
Looks good!  Got 1.1.8.  Thanks again.
