### ISSUE TITLE
How to inject dynamic variables into the linq query

### ISSUE THREAD

**Issue by weedkiller** [PoweredSoft/DynamicLinq#9]
Hi, in this below code, is it possible to have q.Compare(`varAuthorName`, ConditionOperators.Equal, `sizeOfListPull`); since the values could be selected from a web view front end user.

```
query = query.Query(q =>
{
    q.Compare("AuthorId", ConditionOperators.Equal, 1);
    q.And(sq =>
    {
        sq.Compare("Content", ConditionOperators.Equal, "World");
        sq.Or("Title", ConditionOperators.Contains, 3);
    });
});
```

**Comment by dlebee** [comment]
Not sure i understand the question, could you trying being more clear?

**Comment by dlebee** [comment]
I think your answer can be answered if you look at : 
https://github.com/PoweredSoft/DynamicQuery

and there is a sample using it here: https://github.com/PoweredSoft/DynamicQueryAspNetCoreSample

**Comment by weedkiller** [comment]
Hi, guessing you are referring to `handler.ExecuteAsync(query, criteria);` 

I was missing something (but I may have found the answer in filters), since `AuthorId, Content.. ` are hard coded in the previous function Compare call, how can I pass variables/comparable values from a user driven or event driven or windows service at runtime. I think I found it below... I just need the steps to confirm

_______________________________

Solution: After searching, I looked at this [test sample](https://github.com/PoweredSoft/DynamicQuery/blob/a8468e35cadebc032068d8cf2c51d2a41b48c897/PoweredSoft.DynamicQuery.Test/FilterTests.cs#L114) to see if I could dynamically load filter criteria and values.

I didnt see steps on how to build and execute a **dynamic query values** with runtime fed values. So should, I build dynamic composite filters and criteria and feed it to IQueryable? Sorry for the dumb question, I did not see the steps on how to build and run the query. I'm letting a windows service do all that work.

What does IQueryInterceptorProvider do?

1. Step 1 build Filters
2. Step 2 Attach to Composite Filters
3. Steps 3 Build Criteria
4. Step 4 Execute Query

**Comment by dlebee** [comment]
hm it allows to return instance of IQueryInterceptor's which can be hooked at different stages of the handling of the query.

Since this is more related to DynamicQuery though we can chat on the powered soft gitter if you want to have a quicker response?

**Comment by weedkiller** [comment]
sure
